server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.101:8848
    sentinel:
      transport:
        # 配置Sentinel dashboard地址
        dashboard: 192.168.248.101:8080
        # 默认8719端口，键入被占用会自动从8719+1，直到找到未被占用的端口
        port: 8719
      # 配置为false
      web-context-unify: false
      datasource:
        nacos:
          nacos:
            serverAddr: 192.168.248.101:8848
            groupId: DEFAULT_GROUP
            dataId: order-sentinel.json
            ruleType: FLOW

management:
  endpoints:
    web:
      exposure:
        include: '*'