server:
  port: 9003

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.248.101:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'