server:
    port: 9001
spring:
    application:
        name: nacos-provider
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.248.101:8848
management:
    endpoint:
        web:
            exposure:
                include: '*'